### ISSUE TITLE
Can't install Classy Classification due to FastText dependency

### ISSUE THREAD

**Issue by atefalvi** [Pandora-Intelligence/classy-classification#10]
I am trying to install but I keep getting this error. I have tried to install FastText in multiple ways but it seems its no longer supported for py3.9+. Please help. Thank you.

`      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> fasttext`

**Comment by davidberenstein1957** [comment]
I Resolved this issue in 3.2
