### ISSUE TITLE
Exception while saving model

### ISSUE THREAD

**Issue by agurianov** [Pandora-Intelligence/classy-classification#14]
I use the example and got this error:
TypeError: cannot pickle 'onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession' object

**Comment by andremacola** [comment]
More info about this: https://github.com/microsoft/onnxruntime/issues/10097 and https://github.com/microsoft/onnxruntime/pull/800#issuecomment-844326099

**Comment by andremacola** [comment]
I have a dataset with more than 100.000 sentences and labels. Using without pickle is impossible.

However creating the pickle file is time consuming but then it is very quick to raise the api (fastapi) and the response is very fast after being stored in memory.


Using 0.4.2 for now

**Comment by davidberenstein1957** [comment]
https://github.com/Pandora-Intelligence/fast-sentence-transformers/releases/tag/0.3.3

**Comment by davidberenstein1957** [comment]
Thanks! @andremacola

**Comment by davidberenstein1957** [comment]
This will be added to a new release during the coming weekend.
