### ISSUE TITLE
Onnx support on M1 Macs

### ISSUE THREAD

**Issue by andremacola** [Pandora-Intelligence/classy-classification#15]
Unfortunately Onnx is not supported on M1.

Maybe add an alternative when installing the package on Macs with M1 due to the error that occurs? Or even add in Readme to install with homebrew: `brew install cmake` and `brew install protobuf` (I don't know if it works for everyone)

See: https://github.com/onnx/onnx/issues/3129

**Comment by andremacola** [comment]
...and we cannot use pickle with Onnx: https://github.com/Pandora-Intelligence/classy-classification/issues/14

**Comment by andremacola** [comment]
I have a dataset with more than 100.000 sentences and labels. Using without pickle is impossible.

I'm saving the model to a pickle file and the api loads in seconds (no onnx)

**Comment by andremacola** [comment]
I have a dataset with more than 100.000 sentences and labels. Using without pickle is impossible.

I'm saving the model to a pickle file and the api loads in seconds (no onnx)

**Comment by davidberenstein1957** [comment]
https://github.com/Pandora-Intelligence/fast-sentence-transformers/releases/tag/0.3.3

**Comment by davidberenstein1957** [comment]
Not sure either. ONNX provides x5 speed-up out-of the box, so IMO it is worth using. I myself didn´t have any of the installation issues, but perhaps I just got lucky. For now, I added a flag to allow for opting out of using ONNX. 

Thanks for the input!

**Comment by davidberenstein1957** [comment]
This will be added to a new release during the coming weekend.

**Comment by agurianov** [comment]
@davidberenstein1957 Hi, I see errors in the pipeline is it ok?

**Comment by tomaarsen** [comment]
@agurianov It seems to just be flake8 warnings about code formatting. I'll have a look at them.

**Comment by davidberenstein1957** [comment]
I´m still working on some update, but will be able to wrap them up over the weekend.

**Comment by davidberenstein1957** [comment]
The ONNX support was added, but I´m currently re-factoring the entire codebase.
