### ISSUE TITLE
Error when try to save model with pickle (in my local ubuntu linux and in google colab too)

### ISSUE THREAD

**Issue by ximo1984** [Pandora-Intelligence/classy-classification#17]
With the example:
`data = {
    "furniture": ["This text is about chairs.",
               "Couches, benches and televisions.",
               "I really need to get a new sofa."],
    "kitchen": ["There also exist things like fridges.",
                "I hope to be getting a new stove today.",
                "Do you also have some ovens."]
}
classifier = classyClassifier(data=data)

with open("./classifier.pkl", "wb") as f:
    pickle.dump(classifier, f)`

the error is:
TypeError: can't pickle onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession objects

**Comment by andremacola** [comment]
@davidberenstein1957 I think this is related to https://github.com/Pandora-Intelligence/classy-classification/commit/33c4147299dcde705565d8c9b621fb0b0faf4518

**Comment by ximo1984** [comment]
@andremacola thanks,  but these commands are for Mac. I tried uninstalling and installing onxx with "pip install onnx --no-use-pep517" but it didn't work.

You can check it google colab ;)

**Comment by andremacola** [comment]
@ximo1984 The problem is not related to installing onnx but how it is handled with pickle. If I'm not mistaken, it was supposed to have an option to disable onnx in these cases. I think onnx = False is not working on config settings?

**Comment by agurianov** [comment]
@andremacola, Сould you please give moкe details how to turn off onnx from config?

**Comment by davidberenstein1957** [comment]
@agurianov The https://github.com/Pandora-Intelligence/classy-classification/blob/main/classy_classification/classifiers/classy_skeleton.py uses a FastSentenceTransformer with ONNX instead of the default SentenceTransformer. You can replace them if you want.

**Comment by davidberenstein1957** [comment]
@agurianov @andremacola @ximo1984 I added an option to install with or without ONNX in the  0.5.1 release. Via install `classy-classification[onnx]`

**Comment by ximo1984** [comment]
Thanks david.
