### ISSUE TITLE
Hugging face zero shot classifier not working 

### ISSUE THREAD

**Issue by saitej123** [Pandora-Intelligence/classy-classification#2]
![image](https://user-images.githubusercontent.com/18657211/159683973-0f05135b-b026-4c99-aabe-455f6a6917e7.png)
bug in text_categorizer

**Comment by davidberenstein1957** [comment]
Did you import classy_classification?

Could you send some reproducible code?

**Comment by saitej123** [comment]
I have followed same as readme file, imported classy_classfication

**Comment by davidberenstein1957** [comment]
@saitej123 could you send me a `script.py` that you are running, which results in the error and `pip list`.

**Comment by saitej123** [comment]
shared script in another issues, both from same script

**Comment by keithcallenberg** [comment]
@saitej123 I am getting the same error with the same script. Could you explain how you resolved this error?

**Comment by saitej123** [comment]
Hi ,

It will work if you run .py file

Somehow not working in jupyter notebook

**Comment by davidberenstein1957** [comment]
Which version are you using? I think I resolved this in the most recent version.
