### ISSUE TITLE
Is it possible to view training progress?

### ISSUE THREAD

**Issue by drkonafa** [Pandora-Intelligence/classy-classification#23]
Hello! I had a question, I'm using the classifier on a large training data, and as it takes quite sometime even on a GPU it would be great to know if it's progressing and how long I need to wait. Thanks! my sample code below for reference

```
from classy_classification import classyClassifier
import json 
with open('training_data.json') as json_file:
   # Load the JSON data
   data = json.load(json_file)
classifier.set_embedding_model(model="paraphrase-MiniLM-L3-v2")

# overwrite SVC config
classifier.set_classification_model(
    config={
        "C": [1, 2, 5, 10, 20, 100],
        "kernels": ["linear"],
        "max_cross_validation_folds": 5
    }
)

classifier("New text ")



```

**Comment by davidberenstein1957** [comment]
Sadly, it isn´t as off now. I will introduce a verbosity setting next release.

**Comment by davidberenstein1957** [comment]
@drkonafa this was added in the new 0.5.4 release. Happy Holidays 🎄
