### ISSUE TITLE
Drastic performance drop

### ISSUE THREAD

**Issue by hectorhernandezbabbel** [Pandora-Intelligence/classy-classification#35]
Hi @davidberenstein1957,

I was wondering if there were any changes in the past week. I had trained a model that was performing quite well with unseen data and when I loaded it this week it started acting up even with examples from the training data.

Thanks for your support.

**Comment by davidberenstein1957** [comment]
Hi,I reverted the config back into a solution that emperically proved more stable in my testing. I need to setup something more robust for this but will do so when I find the time. When I get back home, I will send you the old configs.CheersOn 20 Feb 2023, at 13:53, hectorhernandezbabbel ***@***.***> wrote:﻿
Hi @davidberenstein1957,
I was wondering if there were any changes in the past week. I had trained a model that was performing quite well with unseen data and when I loaded it this week it started acting up even with examples from the training data.
Thanks for your support.

**Comment by hectorhernandezbabbel** [comment]
I'd really appreciate that. Thanks a lot!

**Comment by davidberenstein1957** [comment]
```python
config = {
    "C": [1, 2, 5, 10, 20, 100],
    "kernel": ["linear", "rbf", "poly"],
    "max_cross_validation_folds": 5,
    "seed": None,
}
```

**Comment by hectorhernandezbabbel** [comment]
Thank you so much!

**Comment by hectorhernandezbabbel** [comment]
I have one more question @davidberenstein1957. Should this be included in the setup?

This is how I'm declaring it, but I don't think it's correct as I'm getting a ConfigValidationError´

nlp.add_pipe("text_categorizer", 
    config={
        "C": [1, 2, 5, 10, 20, 100],
        "kernel": ["linear", "rbf", "poly"],
        "max_cross_validation_folds": 5,
        "seed": None,
        "data": summary_tag,
        "model": "spacy",
         "multi_label": True,
    }
)
```
Thanks for the support again!
