### ISSUE TITLE
Omitting the report message

### ISSUE THREAD

**Issue by newjessar** [Pandora-Intelligence/classy-classification#5]
Hey, Thank you very much for your fantastic workmate.

Please, is there a way to prevent the algorithm from printing the report at the end?

"Fitting two folds for each of 6 candidates, totalling 12 fits."

Yours sincerely

Jay

**Comment by davidberenstein1957** [comment]
@newjessar resolved.

**Comment by newjessar** [comment]
Thank you for fixing the issue!!!
But, I'm really sorry but I have to submit my assignment in two hours and I am not sure what should I do now to have your fix! Please will you guide me? 
Thanx in advance

**Comment by davidberenstein1957** [comment]
@newjessar 
`pip install classy-classification==0.4.2`

**Comment by newjessar** [comment]
Thank you for the respond but it did not work.
