### ISSUE TITLE
How do i get acces to the score of each label?

### ISSUE THREAD

**Issue by luisvfb1** [Pandora-Intelligence/classy-classification#9]
Hello there,

i am currently working on a little Project and i really liked the simplicity of Classy-classification. Now to my issue: Is there a possibility to get acces to the bare prediction score of each label for example to round them up or to just show the top 3? I would be really grateful for some help. 

Thanks for reading and i wish everyone a good day or a good tomorrow.

**Comment by davidberenstein1957** [comment]
@luisvfb1 Great to hear you like the package, but isn't the score returned within the a listed dictionary?
`{'politics': 0.923648738300216, 'sports': 0.04732294344192675, 'weather': 0.029028318257857365}`
`[{'politics': 0.9233572151618138, 'sports': 0.04672762850713562, 'weather': 0.029915156331050474}, {'politics': 0.11478798944099855, 'sports': 0.8152577274452596, 'weather': 0.06995428311374183}, {'politics': 0.033245406437240436, 'sports': 0.18517042379585905, 'weather': 0.7815841697669008}]`
